config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'nosotros', to: 'about#index', as: :nosotros
  get 'servicios', to: 'services#index', as: :servicios
  get 'trabajos', to: 'jobs#index', as: :trabajos
  get 'contacto', to: 'contact#index', as: :contacto
  post 'contacto', to: 'contact#create'

  get 'galerias/:slug', to: 'category#show', as: :galeria
  get 'galerias', to: 'category#index', as: :galerias


  root 'home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :images
  has_many :posts
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :telefono, :email, :content

  validates :name,
    presence: true

  validates :telefono,
    presence: true
    
  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id          :integer          not null, primary key
#  image       :string(255)
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Image < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
  
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  slug        :string(255)
#  content     :text(65535)
#  status      :integer
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :category

  def status_enum
     [['Visible', 1],['Borrador',0]]
  end
  scope :visibles, -> (){
    where(status: 1).order(created_at: :desc)
  }

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    redirect_to galerias_path unless params[:slug].present?
    @category = Category.find_by(slug: params[:slug])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      send = ContactMailer.new_contact(@contact).deliver
      if send
        redirect_to contacto_path, notice: "Mensaje Enviado!"
      else
        flash[:alert] = "Ups, no se ha enviado!"
      end
    else
      flash[:alert] = "Ups, te has dejado algo!"
      render :index
    end
  end

private

  def contact_params
    params.require(:contact).permit(:name, :telefono, :email, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/about/index.html.erb
<% title 'Nosotros' %>
<div class="page nosotros">
  <div class="container">
    <div class="box">

      <div class="row">
        <div class="col-md-7">
          <div class="text">
            <h1 class="title">¿Quíen es Descolga2?</h1>
            <p>
              Somos una empresa especializada en la rehabilitación de edificios y trabajos de difícil acceso, con más de 12 años de experiencia, nos diferenciamos por la realización de los trabajos mediante  el sistema de Trabajos Verticales (descuelgue vertical con cuerdas en suspensión).
            </p>
            <p>
              Si fuere más conveniente, también podemos emplear otros medios como andamios tubulares o colgantes.
            </p>
            <p>
              Nuestra filosofía profesional se define por realizar los proyectos como si nosotros mismos fuéramos los clientes, ofreciendo total disponibilidad y una cercanía absoluta.
            </p>
            <p>
              Todo nuestro equipo cuenta con la formación adecuada para realizar dichos trabajos. Para nosotros es muy importante la seguridad laboral por lo que nuestro personal son Técnicos especialistas en seguridad en altura. Cumpliendo en todo momento con la normativa vigente.
            </p>
            <p>
              Ponemos a su disposición el más completo servicio de trabajos verticales en valencia, con máxima eficacia, rapidez y buen precio.
            </p>
          </div>
        </div>
        <div class="col-md-4">
          <%= image_tag("nosotros.JPG", :alt => "Descolga2") %>
        </div>
      </div>
      <div class="row blocks">
        <div class="col-md-12">
          <h2 class="title">VENTAJAS TRABAJOS VERTICALES</h2>
          <p>Una nueva forma de solucionar trabajos, anteponiendo la seguridad y las ventajas del trabajo en altura, en comparación con sistema de trabajo mas tradicionales</p>
        </div>
      </div>
      <div class="row items">
        <div class="col-md-3">
          <div class="item">
            <h3 class="title">Rápidez</h3>
            <p>
              Al minimizar el tiempo de instalación de los sistemas necesarios para llevar a cabo el trabajo, se reduce en mucho lo que se tarda en acometer la obra.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <h3 class="title">Seguridad</h3>
            <p>Seguridad, el operario siempre está atado, contamos con niveles de siniestralidad cero. Ademas como no hay andamios, no hay posibilidad de que algún intruso se cuele en el edificio durante la obra. </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <h3 class="title">Eficacia</h3>
            <p>Muy adecuado para llegar a sitios difíciles, ya que se puede acceder a áreas en las que es prácticamente imposible instalar un andamio, sin causar molestias a los inquilinos y en el menor tiempo posible</p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <h3 class="title">Ahorro</h3>
            <p>Suponen un ahorro para los vecinos del inmueble, ya que los costes de los trabajos se reducen en gran medida porque todo el proceso se puede realizar de manera más ágil y rápida. </p>
          </div>
        </div>
      </div>

    </div>
    <div class="separator"></div>
  </div>

</div>

app/views/category/_category.html.erb
<div class="row category">
  <div class="col-md-12">
    <% if multi %>
    <div class="row titulo">
      <div class="col-md-12">
        <h2 class="title"><%= link_to category.title.capitalize, galeria_path(slug: category.slug) %></h2>
        <div class="separator min hidden"></div>
      </div>
    </div>
    <% end %>
    <div class="row images">
    <% if category.images.length > 0 %>
      <% category.images.each do |image| %>
        <div class="item">
          <a href="#" data-toggle="modal" data-target="#modal-img" data-image="<%= image.image.url %>"><%= image_tag image.image.url, :class => "img-responsive" %></a>
        </div>
      <% end %>
    <% else %>
    <div class="col-md-12">
      <p>No hay imagenes</p>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/category/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="modal-img" tabindex="-1" role="dialog" aria-labelledby="ImageLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="row">
          <div class="col-md-12">
            <img src="#" class="modal-img">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $('#modal-img').on('show.bs.modal', function (event) {
  var a = $(event.relatedTarget)
  var src = a.data('image')
  var modal = $(this)
  modal.find('.modal-img').attr("src", src)
  })
</script>

app/views/category/index.html.erb
<% title 'Trabajos' %>
<div class="page trabajos">
  <div class="container">
    <div class="row head">
      <div class="col-md-12">
        <h2 class="title">Trabajos Realizados</h2>
        <p>Te enseñamos nuestros últimos trabajos realizados.</p>
      </div>
    </div>

    <% if @categories.length > 0 %>
      <% @categories.each do |category| %>

        <%= render "category", category: category, multi: true %>
      <% end%>
    <% else %>
      <p>Ups.No hay Imagenes</p>
    <% end %>


    <div class="separator"></div>
  </div>

</div>
<%= render "modal" %>

app/views/category/show.html.erb
<% title 'Trabajos' %>
<div class="page trabajos">
  <div class="container">
    <div class="row head">
      <div class="col-md-12">
        <h2 class="title"><%= @category.title.capitalize %> <span><%= link_to "Más categorias", galerias_path %></span></h2>

      </div>
    </div>
    <div class="separator min"></div>
    <%= render "category", category: @category, multi: false %>

    <div class="separator"></div>
  </div>

</div>

app/views/contact/index.html.erb
<% title 'Contacto' %>
<div class="page contact">
  <div class="container">
    <div class="row box">
      <h1 class="title">Contacta con nosotros</h1>
      <div class="col-md-4 col-xs-12">

        <%= form_for @contact, url: contacto_path do |form| %>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <%= form.text_field :name, placeholder: "Nombre" %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <%= form.text_field :telefono, placeholder: "Teléfono" %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <%= form.text_field :email, placeholder: "Email" %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12 col-xs-12">
                <%= form.text_area :content, placeholder: "Escríbenos.." %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <%= form.submit "Enviar", :class => 'btn btn-primary' %>
              </div>
            </div>
        <% end %>
        <div class="row">
          <div class="col-md-12 col-xs-12">
            <% flash.each do |name, msg| %>
              <div class="alert <%= name == 'alert' ? 'alert-danger' : 'alert-success' %>">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <%= msg %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-xs-12 text">
        <p>
          Da igual que seas particular o empresa, nuestro equipo te atenderá en la mayor brevedad posible y siempre con la garantía de un trabajo vertical bien hecho.
        </p>
        <p>
          <b>Email: </b><a href="mailto:info@descolga2.com">info@descolga2.com</a>
        </p>
        <p>
          <b>Teléfono: </b><a href="tel:622184190">622.184.190</a>
        </p>
        <p>
          <b>Horario: </b>Lunes a Viernes: 9:00 - 21:00
        </p>
        <p>
          <b>Web: </b><%= link_to 'www.descolga2.com', root_path %>
        </p>

      </div>
      <div class="col-md-2 image hidden">
        <%= image_tag("contacto.JPG", :alt => "Descolga2") %>
      </div>
    </div>
    <div class="separator"></div>
  </div>
</div>

app/views/home/index.html.erb
<% title 'Inicio' %>
<div class="page">
  <div class="slide">
    <%= image_tag("home.png", :alt => "Descolga2") %>
    <div class="box">
      <h1 class="title">Todos pueden, pero la manera de hacerlo nos diferencia. </h1>
    </div>
  </div>
  <div class="container">
    <div class="block">
      <div class="row">
        <div class="col-md-12">
          <h2 class="title">Soluciones desde lo mas alto</h2>
          <p class="sub-title">Descolga2 realizamos todo tipo de soluciones verticales en altura como rehabilitación de fachadas y limpieza de cristales.</p>
        </div>
      </div>
      <div class="row items">
        <div class="col-md-4 item">
          <%= image_tag("runner.png", :alt => "Descolga2") %>
          <h3>Rápidos</h3>
          <%#= link_to 'Conócenos', nosotros_path, class: 'btn btn-lg btn-primary' %>
        </div>
        <div class="col-md-4 item">
        <%= image_tag("save-money.png", :alt => "Descolga2") %>
          <h3>Económicos</h3>
          <%#= link_to 'Pide un presupuesto', contacto_path, class: 'btn btn-lg btn-primary' %>
        </div>
        <div class="col-md-4 item">
          <%= image_tag("check.png", :alt => "Descolga2") %>
          <h3>Eficaces</h3>
            <%#= link_to 'Nuestros servicios', servicios_path, class: 'btn btn-lg btn-primary' %>
        </div>
      </div>
    </div>
  <div class="separator"></div>
  </div>
</div>

app/views/jobs/index.html.erb
<% title 'Trabajos' %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="col-md-3 item">
      <h2 class="title"><%= link_to 'NOSOTROS', nosotros_path %></h2>
      <p>
        Somos una empresa de restauración y rehabilitación de edificios especializados en trabajos verticales.
        Con mas de 10 años de experiencia en el sector. Nos diferenciamos por un trato personalizado, adaptado a las necesidades de cada cliente y proyecto.
        <!-- Siempre investigando y formándonos en nuevos métodos de trabajo. -->
      </p>
    </div>
    <div class="col-md-3 item">
      <h2 class="title"><%= link_to 'SERVICIOS', servicios_path %></h2>
      <p>
        Rehabilitación de fachadas, patios, tejados y cubiertas. Reparacion de forjados Impermeabilización de cubiertas y medianeras. Renovación de bajantes y canalones.
Reparaciones Urgentes. Colocación de redes protectoras, lonas y pancartas.
      </p>
    </div>
    <div class="col-md-3 item contact">
      <h2 class="title"><%= link_to 'CONTACTO', contacto_path %></h2>
      <ul>
        <li><span><%= image_tag("location.png", :alt => "Descolga2", :class => "icon") %></span>
          C/ Fermín y Galan, 98, 46100 Burjassot, Valencia</li>
        <li style="line-height:30px;"><span><%= image_tag("tel.png", :alt => "Descolga2", :class => "icon") %></span>
          622 184 190</li>
        <li style="line-height:30px;"><span><%= image_tag("email.png", :alt => "Descolga2", :class => "icon") %></span>
          <a href="mailto:info@descolga2.com"> info@descolga2.com</a></li>
      </ul>
    </div>
    <div class="col-md-3 item">
      <%= image_tag("loorke.png", :alt => "Loorke") %>
    </div>

  </div>
</footer>
<footer class="bottom-footer">
  <div class="container">
    <div class="col-md-9 col-xs-12 copy">
      <span>&copy; 2016 Descolga2.com | Todos los derechos reservados | <a href="#">Aviso Legal</a></span>
    </div>
    <div class="col-md-3 col-xs-12 text-center">  <span> Developed with <span class="fa fa-heart"></span> By <a href="https://github.com/kloppz">@kloppz</a></span></div>

  </div>
</footer>
<script type="text/javascript">
$(function() { $.support.transition = false; })

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header pull-right">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand hidden-xs" href="#"><%= image_tag("logo_amarillo.png", :alt => "Descolga2") %></a>
    </div>
    <%= link_to 'Descolga2.com', root_path, :class=> 'tit-logo visible-xs' %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class='<%= (current_page?(root_path) ? "active" : "") %>'><%= link_to "INICIO", root_path %></li>
        <li class='<%= (current_page?(nosotros_path) ? "active" : "") %>'><%= link_to "NOSOTROS", nosotros_path %></li>
        <li class='<%= (current_page?(servicios_path) ? "active" : "") %>'><%= link_to "SERVICIOS", servicios_path %></li>
        <li class='<%= (current_page?(galerias_path) ? "active" : "") %>' ><%= link_to "TRABAJOS", galerias_path %></li>
        <li class='<%= (current_page?(contacto_path) ? "active" : "") %>'><%= link_to "CONTACTO", contacto_path %></li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= if content_for?(:title) then yield(:title) + ' | ' end %> Descolga2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>

    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/services/index.html.erb
<% title 'Servicios' %>
<div class="page servicio">
  <div class="container">
    <div class="row box">
      <div class="col-md-12 col-xs-12">
        <div class="col-md-5 col-xs-12 text">
          <h3 class="title">Especialistas en trabajos verticales.</h3>
          <ul class="list">
            <li><a href="#rehabilitacion-edificios">REHABILITACION DE EDIFICIOS</a></li>
            <li><a href="#impermeabilizacion">IMPERMEABILIZACION</a></li>
            <li><a href="#reparaciones-urgentes">REPARACIONES URGENTES</a></li>
            <li><a href="#instalaciones">INSTALACIONES</a><br><span>cambio de bajantes, colocacion carteles..</span></li>
            <li><a href="#otros-servicios">SERVICIOS QUE TAMBIEN OFRECEMOS</a></li>
            <li><a href="#interiores">DISEÑO INTERIORES</a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12 image">
          <%= image_tag("descolga2.png", :alt => "Descolga2", :class => 'logo') %>
          <%= image_tag("servicios.png", :alt => "Descolga2") %>
        </div>
      </div>
    </div>
    <div class="separator"></div>

    <div class="row box" id="rehabilitacion-edificios">
      <div class="col-md-12 col-xs-12">
        <div class="col-md-5 col-xs-12 text">
          <h3 class="title">Rehabilitación de Edificios.</h3>
          <div class="inner">
            <p>
              Realizamos todo tipo de trabajos de rehabilitación de fachadas, desde trabajos puntuales (frentes de forjado, terrazas, ladrillo, piedra, etc.) hasta la rehabilitación integral de fachadas, medianeras y patios de luces.
            </p>
            <p>
              Además podemos imitar todo tipo de detalles y acabados, desde los más tradicionales hasta los más modernos y de vanguardia, consiguiendo siempre una reparación limpia, en la que no se perciban los cambios o diferencias.
            </p>
            <ul>
              <li> Reparaci&oacute;n y pinturas de fachadas, patios de luces y medianeras.</li>
              <li> Reparaci&oacute;n de forjados</li>
              <li> Reparaci&oacute;n y sellado de juntas de dilataci&oacute;n </li>
              <li> Renovacion y reparacion de tejados. </li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 col-xs-12 image">
          <%= image_tag("descolga2.png", :alt => "Descolga2", :class => 'logo') %>
          <%= image_tag("rehabilitacion.jpg", :alt => "Descolga2") %>
        </div>
      </div>
    </div>
    <div class="separator"></div>

    <div class="row box" id="impermeabilizacion">
      <div class="col-md-12 col-xs-12">
        <div class="col-md-5 col-xs-12 text">
          <h3 class="title">Impermeabilizacion</h3>
          <div class="inner">
            <p>
              Realizamos proyectos de impermeabilización de cubiertas planas, tejados, medianeras y espacios con problemas de humedad. Gestionamos el saneamiento, acondicionamiento y aplicación de productos de prevención de humedades. Ofreciendo a nuestros clientes variedad de opciones, adaptándonos siempre a sus necesidades prácticas y económicas.
            </p>
            <ul>
              <li> Plaqueta cerámica, hormigón, terrazos</li>
              <li> Plaquetas flotantes.</li>
              <li> Tela asfáltica</li>
              <li> Acabado en fibra de vidrio, poliéster y clorocaucho. </li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 col-xs-12 image">
          <%= image_tag("descolga2.png", :alt => "Descolga2", :class => 'logo') %>
          <%= image_tag("impermeabilizacion.jpg", :alt => "Descolga2") %>
        </div>
      </div>
    </div>
    <div class="separator"></div>

    <div class="row box" id="reparaciones-urgentes">
      <div class="col-md-12 col-xs-12">
        <div class="col-md-5 col-xs-12 text">
          <h3 class="title">Reparaciones Urgentes</h3>
          <div class="inner">
            <p> Disponemos de un servicio de intervenci&oacute;n r&aacute;pido para situaciones<span>&nbsp; que requieran de una actuaci&oacute;n puntual, a la mayor brevedad. Como pueden ser:</span></p>
            <ul>
              <li>Saneado y reparaci&oacute;n de bufados, desconchados, grietas o elementos inestables en fachadas.</li>
              <li>Rotura de bajantes.</li>
              <li>Filtraci&oacute;n de agua en cubiertas y tejados.</li>
              <li>Goteras.</li>
              <li>Retirada o fijaci&oacute;n de elementos mal anclados en fachadas o en altura.</li>
              <li>Colocaci&oacute;n redes protectoras.</li>
              <li>Revisiones de fachadas con peligro de desprendimiento. </li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 col-xs-12 image">
          <%= image_tag("descolga2.png", :alt => "Descolga2", :class => 'logo') %>
          <%= image_tag("reparaciones.jpg", :alt => "Descolga2") %>
        </div>
      </div>
    </div>
    <div class="separator"></div>

    <div class="row box" id="instalaciones">
      <div class="col-md-12 col-xs-12">
        <div class="col-md-5 col-xs-12 text">
          <h3 class="title">Instalaciones</h3>
          <div class="inner">
            <p>Otro de los servicios especilizados que ofrecemos son las instalaciones de fontaner&iacute;a&nbsp; y publicidad en zonas de dif&iacute;cil acceso.</p>
            <ul>
              <li>Tuber&iacute;as y canalones de evacuaci&oacute;n de agua</li>
              <li>Bajantes aguas fluviales y fecales</li>
              <li>Montantes de agua fr&iacute;a y caliente. </li>
              <li>Limpieza y mantenimiento de r&oacute;tulos en azote</li>
              <li>Tuber&iacute;as de ventilaci&oacute;n, industrial, calderas, chimeneas</li>
              <li>Montaje de pancartas publicitarias.</li>
              <li>Sistemas de disuasi&oacute;n de aves. </li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 col-xs-12 image">
          <%= image_tag("descolga2.png", :alt => "Descolga2", :class => 'logo') %>
          <%= image_tag("instalaciones.png", :alt => "Descolga2") %>
        </div>
      </div>
    </div>
    <div class="separator"></div>

    <div class="row box" id="otros-servicios">
      <div class="col-md-12 col-xs-12">
        <div class="col-md-5 col-xs-12 text">
          <h3 class="title">Servicios que también ofrecemos</h3>
          <div class="inner">
            <span><b>- Mantenimiento de edificios:</b></span>
            <p class="inner">El mantenimiento adecuado es la mejor prevenci&oacute;n de mayores reparaciones. Con sencillas labores de limpieza y repaso de zonas cr&iacute;ticas, las goteras, humedades y otros desperfectos nunca tendr&aacute;n lugar. </p>
            <p class="inner">Contamos con programas de mantenimiento dise&ntilde;ados para comunidades, instituciones y aseguradoras, para ofrecer mantenimientos peri&oacute;dicos de los tejados y cubiertas. Se realizan revisiones mensuales, semestrales o anuales, dependiendo de las necesidades y del presupuesto&nbsp;de cada edificio, adapt&aacute;ndonos en&nbsp;cada caso para hallar los mejores resultados posibles.</p>
            <span><b>-Limpieza de cristales:</b></span>
            <p class="inner"> Mediante t&eacute;cnicas de trabajos verticales, nuestros especialistas en limpieza en altura de edificios y estructuras, reducir&aacute;n el tiempo de los trabajos, ocasionando el menor impacto posible sobre su entorno y su vida cotidiana.</p>
            <span><b>-Pintura en escaleras, rellanos y garajes.</b></span>
          </div>
        </div>
        <div class="col-md-6 col-xs-12 image">
          <%= image_tag("descolga2.png", :alt => "Descolga2", :class => 'logo') %>
          <%= image_tag("cristales.jpg", :alt => "Descolga2") %>
        </div>
      </div>
    </div>
    <div class="separator"></div>

    <div class="row box" id="interiores">
      <div class="col-md-12 col-xs-12">
        <div class="col-md-5 col-xs-12 text">
          <h3 class="title">Reforma y Diseño de Interiores</h3>
          <div class="inner">
            <p>
              Trabajamos en colaboración con el estudio de Diseño Interior  Loorke, especializado en reformas de locales comerciales y viviendas.
            </p>

          </div>
        </div>
        <div class="col-md-6 col-xs-12 image">
          <%= image_tag("descolga2.png", :alt => "Descolga2", :class => 'logo') %>
          <%= image_tag("interiores.png", :alt => "Descolga2") %>
        </div>
      </div>
    </div>
    <div class="separator"></div>

  </div>
</div>
<a href="#" class="scrollToTop">Subir</a>